### PR TITLE
Data Table Component Preview - Pagination Dropdown theme issue

### PR DESCRIPTION
**Pull request by ragul1697**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our
      guidelines: https://github.com/goetzrobin/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] avatar
- [ ] badge
- [ ] button
- [ ] calendar
- [ ] card
- [ ] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [x] data-table
- [ ] date-picker
- [ ] dialog
- [ ] dropdown-menu
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] skeleton
- [ ] slider
- [ ] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toast
- [ ] toggle
- [ ] tooltip
- [ ] typography

## What is the current behavior?

For the Data Table pagination dropdown, the selection list UI does not match the system's current theme.  It remains at light background when the dark theme is active.

Closes #

## What is the new behavior?
The Data table page dropdown now matches with the system theme.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by elite-benni** [comment]
Thanks for the PR.
We were usually planning to replace the select with our new select component. 
Would you like to do this instead of setting the background?

**Comment by ragul1697** [comment]
Sure, I will replace it with the select component.

**Comment by ragul1697** [comment]
I have updated the Data Table pagination with the new Select component. There was an issue in the naming of Data Table Page component. It was named as **ComboBoxComponent** and fixed it also.

**Comment by elite-benni** [comment]
We also have some formatting problems here, please make sure to run prettier before pushing. ;) 
I would like to delay this PR until the select is fixed.

**Comment by ragul1697** [comment]
@elite-benni Code Formatting is completed.

**Review by elite-benni — CHANGES_REQUESTED** [review]
Sorry, I just realized that I did not finish my review
can you please change to ngModel?
I hope then we will not have to bother you, once the select fix is pushed. ;)

**Comment by ragul1697** [comment]
@elite-benni I have completed the changes. Please have a look at the code. Thanks for your Time.

**Pull request merged**
