### PR TITLE
feat(docs): adding icon to issue and PR templates 

### LINKED ISSUE #217: Adding icon as a choice in issue and PR templates
### Which scope/s are relevant/related to the feature request?

Docs

### Information

After creating an Icon related feature request I noticed that `icon` is missing as a selection choice from the yml dropdown

### Describe any alternatives/workarounds you're currently using

I have been using `docs` as a choice

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by monacodelisa**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our
      guidelines: https://github.com/goetzrobin/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] avatar
- [ ] badge
- [ ] button
- [ ] calendar
- [ ] card
- [ ] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [ ] dropdown-menu
- [ ] hover-card
- [x] icon
- [ ] input
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] skeleton
- [ ] slider
- [ ] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toast
- [ ] toggle
- [ ] tooltip
- [ ] typography

## What is the current behavior?

Closes #217 

## What is the new behavior?
I should be able to select Icon :) 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by elite-benni — APPROVED** [review]
LGTM

**Review by goetzrobin — APPROVED** [review]

**Comment by goetzrobin** [comment]
We should probably also add it to commitlint. There's a commitlint config file @monacodelisa

**Comment by monacodelisa** [comment]
@goetzrobin ok will look for it

**Comment by monacodelisa** [comment]
@goetzrobin it's actually there in `commitlint.config.cjs` already

**Pull request merged**
