### PR TITLE
feat: update size options height for data table

### LINKED ISSUE #334: Data Table: Table height does't update when size options change
### Please provide the environment you discovered this bug in.

Production

### Which area/package is the issue in?

data-table

### Description

When changing the size from 5 -> 10, it should show more items rather than allowing it to be scrollable which confuses users since it's not a big list. 

data-table-old

### Please provide the exception or error you saw

_No response_

### Other information

_No response_

Example from Material Table

https://material.angular.io/components/table/examples#table-pagination

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by dalenguyen**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our
      guidelines: https://github.com/goetzrobin/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] avatar
- [ ] badge
- [ ] button
- [ ] calendar
- [ ] card
- [ ] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [x] data-table
- [ ] date-picker
- [ ] dialog
- [ ] dropdown-menu
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] skeleton
- [ ] slider
- [ ] sonner
- [ ] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toast
- [ ] toggle
- [ ] tooltip
- [ ] typography

## What is the current behavior?

data-table-old

Closes #334 

## What is the new behavior?

data-table-size

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by goetzrobin** [comment]
@dalenguyen should there be a max size? e.g. when All is selected?

**Comment by dalenguyen** [comment]
> @dalenguyen should there be a max size? e.g. when All is selected?

From the Material table example, I don't see the limit on the height. For `All`, I think it depends on the users. For table with more than thousand rows, having the the `All` option is really inaccessible without the scrollable ability. 

What do you think?

**Comment by goetzrobin** [comment]
> > @dalenguyen should there be a max size? e.g. when All is selected?
> 
> From the Material table example, I don't see the limit on the height. For `All`, I think it depends on the users. For table with more than thousand rows, having the the `All` option is really inaccessible without the scrollable ability.
> 
> What do you think?

I agree and it's only an example so people can adjust it in their code as they need anyways. I'd say let's put a max height so maybe if the user selects all they can get a demo of that?

**Comment by dalenguyen** [comment]
> > > @dalenguyen should there be a max size? e.g. when All is selected?
> > 
> > 
> > From the Material table example, I don't see the limit on the height. For `All`, I think it depends on the users. For table with more than thousand rows, having the the `All` option is really inaccessible without the scrollable ability.
> > What do you think?
> 
> I agree and it's only an example so people can adjust it in their code as they need anyways. I'd say let's put a max height so maybe if the user selects all they can get a demo of that?

Sure, do you have any number in mind? How about 400px?

**Review by elite-benni — APPROVED** [review]

**Comment by dalenguyen** [comment]
Added max height 500px for the demo. Please let me know if it is a good one for the demo purpose 😄

**Pull request merged**
