### PR TITLE
feat(select,spinner,separator,toggle): more input signals

### PR DESCRIPTION
**Pull request by Celtian**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our
      guidelines: https://github.com/goetzrobin/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] avatar
- [ ] badge
- [ ] button
- [ ] calendar
- [ ] card
- [ ] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [ ] dropdown-menu
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] scroll-area
- [x] select
- [x] separator
- [ ] sheet
- [ ] skeleton
- [ ] slider
- [ ] sonner
- [x] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toast
- [x] toggle
- [ ] tooltip
- [ ] typography

## What is the current behavior?

Closes #

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ajitzero** [comment]
Hi, are you converting these manually? There is a reasonably stable CLI migration command for this.

Please take a look: https://twitter.com/Enea_Jahollari/status/1773335882780557471
```shell
npm i ngxtension
ng g ngxtension:convert-outputs
```

**Comment by Celtian** [comment]
> Hi, are you converting these manually? There is a reasonably stable CLI migration command for this.
> 
> Please take a look: https://twitter.com/Enea_Jahollari/status/1773335882780557471
> 
> ```shell
> npm i ngxtension
> ng g ngxtension:convert-outputs
> ```

But there is a problem. Compatibility with Storybook. You can's convert everything right now...

**Comment by ajitzero** [comment]
Ah, that makes sense! Thanks for the info, I hadn't tried it myself yet.

**Comment by elite-benni** [comment]
LGTM! 
Its just so much cleaner this way!

**Pull request merged**
