### PR TITLE
refactor(button): refactor storybook files

### PR DESCRIPTION
**Pull request by DominikPieper**
While I integrate the storybook files into my repository I rework some of their functionality. This PR is just for discussion yet:

Should I reintegrate the changes I do to the Spartan repo? The actual Storybook files are mostly static per story. I refactor them to utilize Storybook a little more and e.g. use controls instead of adding all variants into each story statically. Would that be interesting for someone? I just want to ask before I do all the work :-P

see an small example for the button component

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x ] The commit message follows our
      guidelines: https://github.com/goetzrobin/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [x] accordion
- [x] alert
- [x] alert-dialog
- [x] aspect-ratio
- [x] avatar
- [x] badge
- [x] button
- [x] calendar
- [x] card
- [x] checkbox
- [x] collapsible
- [x] combobox
- [x] command
- [x] context-menu
- [x] data-table
- [x] date-picker
- [x] dialog
- [x] dropdown-menu
- [x] hover-card
- [x] input
- [x] label
- [x] menubar
- [x] navigation-menu
- [x] popover
- [x] progress
- [x] radio-group
- [x] scroll-area
- [x] select
- [x] separator
- [x] sheet
- [x] skeleton
- [x] slider
- [x] switch
- [x] table
- [x] tabs
- [x] textarea
- [x] toast
- [x] toggle
- [x] tooltip
- [x] typography

## What is the current behavior?

Closes #

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ajitzero** [comment]
I was wondering about the same! I'm very new to Storybook in general, so I wasn't sure about the approach, but your changes definitely look great :)

Maybe some confirmation from @goetzrobin  @elite-benni?

**Comment by DominikPieper** [comment]
Extended it, unfortunately it’s more than one component in this pr 😅

**Comment by elite-benni** [comment]
This confirmation has to come from @goetzrobin ;). 
I am also pretty new to storybook and just added stories in the previous existing style. 
To me, it looks like yours is the cleaner and better approach and definately improves dx and readability. 

Info: Also look at the e2e tests when you do the changes, because they rely on the stories.

**Comment by DominikPieper** [comment]
@elite-benni  thanks, I’ll keep the tests in mind

**Comment by goetzrobin** [comment]
Agree with everything said here! I think those stories are great! Let's adopt them as the standard way for new primitives 😍 @DominikPieper as @elite-benni mentioned, the e2e tests are built around the stories so we'll have to adjust those!

**Comment by DominikPieper** [comment]
I’ll take a look at the tests after I’m done with all Stories

**Comment by DominikPieper** [comment]
@goetzrobin I'm done (for now). Refactored most of the stories a little to make them interactive. The e2e tests work too. (slightly modifications for one test, it's splitted up now a test by "state")

**Comment by goetzrobin** [comment]
Awesome! Checking this out now! Excited to get this merged!

**Pull request merged**
