### PR TITLE
feat(accordion): add hlm-accordion-content component

### PR DESCRIPTION
**Pull request by marcjulian**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our
      guidelines: https://github.com/goetzrobin/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [X] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] avatar
- [ ] badge
- [ ] button
- [ ] calendar
- [ ] card
- [ ] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [ ] dropdown-menu
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] skeleton
- [ ] slider
- [ ] sonner
- [ ] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toast
- [ ] toggle
- [ ] tooltip
- [ ] typography

## What is the current behavior?

Using `brn-accordion-content` along with helm accordion directives.

```html
<div hlmAccordionItem>
  <button hlmAccordionTrigger>
    Is it accessible?
    <hlm-icon hlmAccIcon />
  </button>
  <brn-accordion-content hlm>Yes. It adheres to the WAI-ARIA design pattern.</brn-accordion-content>
</div>

```

## What is the new behavior?

Adds a new `HlmAccordionContentComponent` to combine `BrnAccordionContentComponent` and `HlmAccordionContentDirective` into a component.

Usage with `HlmAccordionContentComponent` looks like this

```html
<div hlmAccordionItem>
  <button hlmAccordionTrigger>
    Is it accessible?
    <hlm-icon hlmAccIcon />
  </button>
  <hlm-accordion-content>Yes. It adheres to the WAI-ARIA design pattern.</hlm-accordion-content>
</div>
```

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by goetzrobin** [comment]
@marcjulian do you know why the e2e tests are timing out?

**Comment by marcjulian** [comment]
@goetzrobin not sure why the e2e test are timing out in CI. They run fine locally.

**Comment by marcjulian** [comment]
I found the reason for the failing e2e tests.

This is because I use in `HlmAccordionContentComponent` the `BrnAccordionContentComponent` in the template rather than extending `HlmAccordionContentComponent` with it.

```html
// hlm-accordion-content
<brn-accordion-content [class]="_computedClass()">
    <ng-content />
</brn-accordion-content>
```

Thus the `hlm-accordion-content` has no `role`, `data-*` nor `aria-*`, thus are all applied to `brn-accordion-content`.

CleanShot 2024-08-20 at 11 04 38

When I extend `HlmAccordionContentComponent` with `BrnAccordionContentComponent` the logic works, but the template is overridden from `HlmAccordionContentComponent`. I copied over the content from the brn accordion content, not sure if that is the desired solution here.

**Comment by goetzrobin** [comment]
@marcjulian not ideal but since the logic in the template is pretty minimal let's go ahead with this as we are working around an Angular intricacy here

**Pull request merged**
