### PR TITLE
refactor: change input signals to public

### PR DESCRIPTION
**Pull request by miljan-code**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our
      guidelines: https://github.com/goetzrobin/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

multiple

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] avatar
- [ ] badge
- [ ] button
- [ ] calendar
- [ ] card
- [ ] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [ ] dropdown-menu
- [ ] hover-card
- [ ] input
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] skeleton
- [ ] slider
- [ ] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toast
- [ ] toggle
- [ ] tooltip
- [ ] typography

## What is the current behavior?

Input signals are private members, so the typescript is complaining whenever we try to add custom class on a component.

spartan

## What is the new behavior?

Input signals are public members.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by elite-benni** [comment]
That is interesting. 
We had a similar problem for a short period of time. I am still not sure what causes this. 
I guess just making them public is the way to go. 
Can you please remove the underscore too, because this is usually used for private and protected.

**Comment by goetzrobin** [comment]
Do you guys think we should move to model inputs instead?

**Comment by thatsamsonkid** [comment]
> Do you guys think we should move to model inputs instead?



> Do you guys think we should move to model inputs instead?

**Comment by elite-benni** [comment]
Hey @miljan-code, 
we discussed this, and we would like to keep it as inputs, but it would be nice if you could remove the underscores. 
Can you please change this?

**Comment by goetzrobin** [comment]
@miljan-code sorry about the conflicts... took me a while to get back to this PR. Can you resolve them and I'll merge asap

**Review by elite-benni — APPROVED** [review]
Thanks for removing the underscores and thanks for the change.

**Pull request merged**
