### PR TITLE
Refactor: Replace @HostBinding with host property of Component Decorator

### LINKED ISSUE #55: Refactor Hostbinding to host property in the @Component decorator
As stated in the angular.dev docs:

Always prefer using the host property over [@HostBinding](https://angular.dev/api/core/HostBinding) and [@HostListener](https://angular.dev/api/core/HostListener). These decorators exist exclusively for backwards compatibility.

Im gonna tackle this.

### PR DESCRIPTION
**Pull request by elite-benni**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our
      guidelines: https://github.com/goetzrobin/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [x] accordion
- [x] alert
- [x] alert-dialog
- [x] aspect-ratio
- [x] avatar
- [x] badge
- [x] button
- [x] calendar
- [x] card
- [x] checkbox
- [x] collapsible
- [x] combobox
- [x] command
- [x] context-menu
- [x] data-table
- [x] date-picker
- [x] dialog
- [x] dropdown-menu
- [x] hover-card
- [x] input
- [x] label
- [x] menubar
- [x] navigation-menu
- [x] popover
- [x] progress
- [x] radio-group
- [x] scroll-area
- [x] select
- [x] separator
- [x] sheet
- [x] skeleton
- [x] slider
- [x] switch
- [x] table
- [x] tabs
- [x] textarea
- [x] toast
- [x] toggle
- [x] tooltip
- [x] typography

## What is the current behavior?

The Binding of the Class is set to Host with a @HostBinding, which is not the preverred approach as stated in angular.dev.
@HostBinding also does not work with onPush Parent Components and changes to the property. 

Closes #

## What is the new behavior?

The classes are bound to the host property of the component decorator.
Signals or computed that are bound via host property also work with changes.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
I also implemented the userCls signal in every Component with the same structure, so we should not have a too hard time when migrating to signal based inputs. 
closes #55

### CODE REVIEW

**Comment by goetzrobin** [comment]
Looks good to me! There is a tiny conflict after merging a different PR, once you fix that one I will merge it!

**Comment by goetzrobin** [comment]
@elite-benni Thank you! That was fast! 
Noticed another minor thing: Can we make all the signals readonly. Just to add a layer of "security" as signals are not meant to be reassigned.

**Review by nartc — APPROVED** [review]
LGTM. Though I have a non-blocking question, some places still use `generateClasses()` private method while some other places don't. Can we make this more consistent?

**Comment by elite-benni** [comment]
Sure, I can do this. 
The generateClasses() that are left are because it was easier to replace the old code. 

The whole idea of this change was to make it more consistent. Thanks for pointing that out. 
I think keeping generateClasses everywhere, is easier to read. 

I will add readonly to the signals.

**Comment by elite-benni** [comment]
I merged the conflict in github. ;) thats why i missed the empty line ;)

**Comment by goetzrobin** [comment]
🚀  Thanks for making those changes!

**Pull request merged**
