### PR TITLE
fix(checkbox): the native input position has been changed to 'fixed'

### PR DESCRIPTION
**Pull request by elite-lucas**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x ] The commit message follows our
      guidelines: https://github.com/goetzrobin/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] avatar
- [ ] badge
- [ ] button
- [ ] calendar
- [ ] card
- [x ] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [ ] dropdown-menu
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] skeleton
- [ ] slider
- [ ] sonner
- [ ] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toast
- [ ] toggle
- [ ] tooltip
- [ ] typography

## What is the current behavior?

ISSUE: Checkboxes within a scrollarea #324

Closes #

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

## Other information
pickA
pickB
pickC

### CODE REVIEW

**Comment by goetzrobin** [comment]
We should give the parent element a position of relative instead of fixed. Let's also make it configurable so users can override the behavior if they'd like to

**Comment by goetzrobin** [comment]
@elite-lucas please let me know if you need help with this

**Comment by elite-lucas** [comment]
Hello, sorry for the late reply. As I am on vacation, I am unfortunately unable to work on the Chechbox for the next 3 weeks.
Greetings Lucas

**Comment by goetzrobin** [comment]
I'll take a crack at this

**Pull request closed without merging**
