### PR TITLE
chore: update to Nx 19.6.5 and Analog 1.7.3

### PR DESCRIPTION
**Pull request by benpsnyder**

### CODE REVIEW

**Comment by benpsnyder** [comment]
@goetzrobin pleas authorize vercel so I can proceed

**Comment by goetzrobin** [comment]
> @goetzrobin pleas authorize vercel so I can proceed

Done!

**Comment by benpsnyder** [comment]
> > @goetzrobin pleas authorize vercel so I can proceed
> 
> Done!

@goetzrobin unfortunately there is still some issue

**Comment by goetzrobin** [comment]
image

**Comment by benpsnyder** [comment]
@goetzrobin lol ... my bad ... I'll fix in a few hours. That was a GPT error. I was rushing to get to a family party

**Comment by goetzrobin** [comment]
No worries! Enjoy the party! 🎉🎉

**Comment by benpsnyder** [comment]
Almost there now ... just need to fix these e2e tests
image

**Comment by benpsnyder** [comment]
@goetzrobin this is ready to go .... I would request to open issues and fix the few tests I commented out in follow-up PRs.

These can be found by searching `/* TODO: @goetzrobin`

**Pull request merged**
