### PR TITLE
feat(repo): fix build errors in nitropack and during server and static page rendering

### PR DESCRIPTION
**Pull request by benpsnyder**
Completed:
- [x] #275 -- Resolves sufficiently because this isn't something we have to worry about and we shouldn't see the console littered with deprecation messages. It will be resolved upstream with nitropack.
- [x] #272 -- easily resolves by bumping the package version due to https://github.com/angular/cdk-builds/commit/b993db89f8368e2ddf97685b9d0dedbb2d8bde51 being addressed

WIP:
- [ ] #274
- [ ] #271 
- [ ] #273

### CODE REVIEW

**Comment by goetzrobin** [comment]
@benpsnyder is this good to go?

**Comment by goetzrobin** [comment]
@benpsnyder is this still needed?

**Comment by benpsnyder** [comment]
Let me check on it by tomorrow; I will do some housecleaning in the repo here

**Comment by goetzrobin** [comment]
@benpsnyder I'll close this PR for now. Once you have the time and capacity to resolve the conflicts feel free to update and reopen!

**Pull request closed without merging**
