### PR TITLE
feat(pagination): add pagination

### LINKED ISSUE #119: RFC: Pagination
### Which scope/s are relevant/related to the feature request?

pagination

### Information

# Pagination

### Aria
1. use nav,  role="navigation", aria-label="pagination"
2. use ul & li
3. use a-tag & aria-current= "page"

## Shadcn

```jsx
import * as React from "react"
import {
  ChevronLeftIcon,
  ChevronRightIcon,
  DotsHorizontalIcon,
} from "@radix-ui/react-icons"

import { cn } from "@/lib/utils"
import { ButtonProps, buttonVariants } from "@/components/ui/button"

const Pagination = ({ className, ...props }: React.ComponentProps<"nav">) => (
  <nav
    role="navigation"
    aria-label="pagination"
    className={cn("mx-auto flex w-full justify-center", className)}
    {...props}
  />
)
Pagination.displayName = "Pagination"

const PaginationContent = React.forwardRef<
  HTMLUListElement,
  React.ComponentProps<"ul">
>(({ className, ...props }, ref) => (
  <ul
    ref={ref}
    className={cn("flex flex-row items-center gap-1", className)}
    {...props}
  />
))
PaginationContent.displayName = "PaginationContent"

const PaginationItem = React.forwardRef<
  HTMLLIElement,
  React.ComponentProps<"li">
>(({ className, ...props }, ref) => (
  <li ref={ref} className={cn("", className)} {...props} />
))
PaginationItem.displayName = "PaginationItem"

type PaginationLinkProps = {
  isActive?: boolean
} & Pick<ButtonProps, "size"> &
  React.ComponentProps<"a">

const PaginationLink = ({
  className,
  isActive,
  size = "icon",
  ...props
}: PaginationLinkProps) => (
  <a
    aria-current={isActive ? "page" : undefined}
    className={cn(
      buttonVariants({
        variant: isActive ? "outline" : "ghost",
        size,
      }),
      className
    )}
    {...props}
  />
)
PaginationLink.displayName = "PaginationLink"

const PaginationPrevious = ({
  className,
  ...props
}: React.ComponentProps<typeof PaginationLink>) => (
  <PaginationLink
    aria-label="Go to previous page"
    size="default"
    className={cn("gap-1 pl-2.5", className)}
    {...props}
  >
    <ChevronLeftIcon className="h-4 w-4" />
    <span>Previous</span>
  </PaginationLink>
)
PaginationPrevious.displayName = "PaginationPrevious"

const PaginationNext = ({
  className,
  ...props
}: React.ComponentProps<typeof PaginationLink>) => (
  <PaginationLink
    aria-label="Go to next page"
    size="default"
    className={cn("gap-1 pr-2.5", className)}
    {...props}
  >
    <span>Next</span>
    <ChevronRightIcon className="h-4 w-4" />
  </PaginationLink>
)
PaginationNext.displayName = "PaginationNext"

const PaginationEllipsis = ({
  className,
  ...props
}: React.ComponentProps<"span">) => (
  <span
    aria-hidden
    className={cn("flex h-9 w-9 items-center justify-center", className)}
    {...props}
  >
    <DotsHorizontalIcon className="h-4 w-4" />
    <span className="sr-only">More pages</span>
  </span>
)
PaginationEllipsis.displayName = "PaginationEllipsis"

export {
  Pagination,
  PaginationContent,
  PaginationLink,
  PaginationItem,
  PaginationPrevious,
  PaginationNext,
  PaginationEllipsis,
}
```

### Source

https://ui.shadcn.com/docs/components/pagination

### Other Considerations

Since we rely on html tags here to drive accessibility we should probably make most of the styling come from directives

### Describe any alternatives/workarounds you're currently using

_No response_

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by marcjulian**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our
      guidelines: https://github.com/goetzrobin/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] avatar
- [ ] badge
- [ ] button
- [ ] calendar
- [ ] card
- [ ] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [ ] dropdown-menu
- [ ] hover-card
- [ ] input
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [X] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] skeleton
- [ ] slider
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toast
- [ ] toggle
- [ ] tooltip
- [ ] typography

## What is the current behavior?

Closes #119 

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by marcjulian** [comment]
I would like your feedback on how we should implement previous/next. I added it as component but now I would need to handle passing `href` or `routerLink`.

Open tasks

- [ ] update storybook
- [ ] copy pagination to cli

**Comment by goetzrobin** [comment]
> I would like your feedback @goetzrobin on how we should implement previous/next. I added it as component but now I would need to handle passing `href` or `routerLink`.
> 
> Open tasks
> 
> * [ ]  update storybook
> * [ ]  copy pagination to cli

Interesting question.... My mind went to thinking that you can just go with providing both as inputs (href & routerLink) and under the hood determine to use routerLink or href. Although if we pick one for now I'd go with routerLink as this is pretty much the default of how we link in Angular apps.

**Comment by marcjulian** [comment]
Okay i added `href` as input to Next and Previous component, using `routerLink` for navigation. 
I guess `routerLink` is the better approach anyways, the pagination probably never points to an external page.

**Comment by goetzrobin** [comment]
@marcjulian looking at your example now I think we should change it to router link and also add support for the additional router link option inputs. Your argument that this will most likely always be internal navigation makes sense! Sorry about the change of mind here!

**Comment by marcjulian** [comment]
If I rename the input to `routerLink` it will act as input and as directive in the preview.

CleanShot 2024-02-01 at 10 38 12

The `routerLink` directive will be applied to `hlm-pagination-previous` and passed as input to the component and then applied to the anchor tag.

CleanShot 2024-02-01 at 10 39 12

I see following options:

1. Move `a` tag out from `hlm-pagination-previous/next` and wrap the component in template with `a` tag
2. Rename to `routerlink` to avoid applying the directive too

With approach 1. the user has full access to the anchor tag in the template, with 2. we would need to handle the additional router link options.

**Comment by goetzrobin** [comment]
> If I rename the input to `routerLink` it will act as input and as directive in the preview.
> 
> CleanShot 2024-02-01 at 10 38 12
> 
> The `routerLink` directive will be applied to `hlm-pagination-previous` and passed as input to the component and then applied to the anchor tag.
> 
> CleanShot 2024-02-01 at 10 39 12
> 
> I see following options:
> 
> 1. Move `a` tag out from `hlm-pagination-previous/next` and wrap the component in template with `a` tag
> 2. Rename to `routerlink` to avoid applying the directive too
> 
> With approach 1. the user has full access to the anchor tag in the template, with 2. we would need to handle the additional router link options.

@marcjulian Very good points. Maybe we stay with href or just do [link]="#" [linkOptions]="{ROUTER_OPTIONS_HERE}" ? I am open to hear your suggestion! We would also make routerlink a host directive for hlmPaginationLink and keep the same  [link]="#" [linkOptions]="{ROUTER_OPTIONS_HERE}" inputs that are forwarded to routerlink? That way the API stays consitent?

**Comment by marcjulian** [comment]
@goetzrobin the idea with `RouterLink` as host directive for `HlmPaginationLinkDirective` is a really good idea! Haven't used it yet, really powerful! 

I would prefer going with `link` as input for `routerLink`, as it is closer than `href`.

Which router link options do you mean should be exposed with `linkOptions` as input? Should we add all [RouterLink inputs](https://angular.io/api/router/RouterLink#properties) to the host directive and keeping the name?

For example


```ts
@Directive({
	selector: '[hlmPaginationLink]',
	standalone: true,
	hostDirectives: [
		{
			directive: RouterLink,
			inputs: ['routerLink: link', 'queryParams',  'fragment' ...], // 👈
		},
	],
	host: {
		'[class]': '_computedClass()',
		'[attr.aria-current]': 'isActive() ? "page" : null',
	},
})
export class HlmPaginationLinkDirective {
```

**Comment by goetzrobin** [comment]
@marcjulian I'd say we keep all of them! Let's do link! I like it!!

**Comment by marcjulian** [comment]
I run `prepare-cli` to copy hlm to cli. `HlmPaginationLinkDirective` uses `buttonVariants`, relying on the button component. Do I need to add this relationship somewhere to the CLI or how is it handled?

**Comment by marcjulian** [comment]
@goetzrobin I think I have found it. Please try it out and let me know what to do next.

**Pull request merged**
